spring:
  datasource:
    url: jdbc:mysql://dhskdb.c3yqgc6icsss.ap-southeast-1.rds.amazonaws.com:3306/dhskdb?allowPublicKeyRetrieval=true&useSSL=false
    username: "admin"
    password: "mysql123"
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      globally_quoted_identifiers: true